### PR TITLE
Fix broken wallet address for 500 ruppees cheat

### PR DESCRIPTION
**Pull request by Column01**
Address was set to 10776318 and not 10775318 (correct address)

Confirmed working after finding it not working.
See https://github.com/FlagBrew/Sharkive/edit/master/3ds/0004000000125500.txt#L5 for the correct address which I used.

### CODE REVIEW

**Comment by Column01** [comment]
Looking at it, the bank address is also broken but I do not know how to find the right ones

**Comment by Column01** [comment]
Using citra so IDK if that changes things...

**Comment by JourneyOver** [comment]
It could be, I'd suggest trying the codes on an actual 3DS and letting me know if they work, before I go about accepting this PR.

**Comment by SpiredMoth** [comment]
It would also help if you note what game version you're using, since v1.0 can have different offsets for things compared to v1.1

**Comment by Column01** [comment]
For sure the first one is a typo since the only change should be the value to move in but the bank address I have no idea where to start with that.
I think it's v1.1

**Comment by JourneyOver** [comment]
When Spired said to note what game version he means in the name of the cheat in the file.

Well I can't really say if I can accept this or not until it gets tested on a 3DS, due to the fact that sometimes codes differ when it comes to them being used on citra vs an actual 3DS (it's one reason why there are codes out there in the wild that are marked as citra only).

**Comment by JourneyOver** [comment]
Going to go ahead and close this, I decided to look up the code finally anyways and instead of it being 500 Rupees it's supposed to be inf rupees instead at least going by [this post](https://gbatemp.net/threads/gateway-cheats.402900/page-22#post-5896867), so I'll get around to fixing said name.

**Pull request closed without merging**
