### PR TITLE
Added new Codes to EUR Ice Station Z 

### PR DESCRIPTION
**Pull request by Cracko298**

### CODE REVIEW

**Comment by GriffinG1** [comment]
Have you tested all these codes and can confirm they all work?

**Comment by Cracko298** [comment]
I've created and tested them using CTRPF v0.7.2 and they all work with no hitches. If you need screenshots I can get those asap.

Sent from my T-Mobile 4G LTE Device
Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by JourneyOver** [comment]
How about testing with Luma's cheat engine as well? believe there are still some differences between the two that some codes may not work on the cheat engine, while working on CTRPF.

**Comment by Cracko298** [comment]
The only code that doesn't work with the "All Ammo Generator"

Below are some images to show the plugin working.
image
image
image
image

**Comment by JourneyOver** [comment]
Okay kindly remove the 1 cheat that doesn't work or rework it so it works in lumas cheat menu as well, then I will gladly merge this in.

**Comment by Cracko298** [comment]
Just removed the code that didn't work with Luma's Cheat Engine.

**Comment by JourneyOver** [comment]
Thank you, will go ahead and merge it now.

**Pull request merged**
