### PR TITLE
Collected cheat codes added

### PR DESCRIPTION
**Pull request by Firefox2100**
I added some of the cheat codes I've found online. They've all been tested on my console and worked. However I didn't write these codes and couldn't find any information regarding the original creator, they're simply redistributed on different sites as I found them.

### CODE REVIEW

**Comment by JourneyOver** [comment]
When you say you tested them on your console and they worked, do you mean you tested them in luma's cheat menu or did you test them in CTRPF? As I recall seeing some of these cheats before being in the database and they had been removed because of various reasons like being broken and such.

Also please remove any notes, any [++name++], any [--] as luma's cheat menu does not support them.

**Comment by JourneyOver** [comment]
@Firefox2100 are you ever going to respond to this? Going to give it a couple more days and then I'm going to possibly close this if I haven't had a response.

**Comment by Firefox2100** [comment]
Sorry that I've been working recently and hadn't had the time to check my inbox. I've tested them in the Luma cheat menu, the one you can bring up with L+down+select, and they worked. Sometimes for some unknown reason, one or more of some codes may turn red, just simply exit the game and re-enter, and they'll function properly again. This is probably due to some memory allocation mechanism the game uses. I'll remove the names and comments right away

**Comment by JourneyOver** [comment]
There is still a bunch of stuff that needs to be removed. You still have cheats that have notes, cheats that have japanese above the cheat name, cheats that just won't work as they require the user to go in and edit the code themself, a list that has the name and TitleID in the list with all the cheats.

All this stuff needs to be removed before I even think about accepting this into the repo.

**Comment by Firefox2100** [comment]
In that case maybe I should close this myself, rather than messing around with the database and cheats

**Pull request closed without merging**
