### PR TITLE
Added code to access unused CPU opponent in Tetris Axis

### PR DESCRIPTION
**Pull request by TheLadyOfBees**
Hello!

Documenting a game over at TCRF and wanting to add in a code that accesses hidden content. I'm fairly sure I'm supposed to make a pull request to master looking at your branches, but let me know if I'm wrong.

Cheers!

### CODE REVIEW

**Comment by JourneyOver** [comment]
Since I see a file called `.directory` that is mentioning dolphin, have you confirmed that this works with luma's cheat engine? and also before I merge anything you will need to remove the `.directory` file.

**Comment by TheLadyOfBees** [comment]
Oh golly dolphin would be my file browser. It has some git intigration so that is probably what's happening. I'll remove that and commit my bad. And yes this works with luma's cheat engine

**Comment by TheLadyOfBees** [comment]
Should be all fixed now

**Comment by JourneyOver** [comment]
LGTM - thanks

**Pull request merged**
