### PR TITLE
Added cheats for all versions of Fire Emblem Echoes

### PR DESCRIPTION
**Pull request by Anaklumos12**
Cheats for the EUR and USA versions updated to work in version 1.1,  added JP cheat codes also for version 1.1.

Tested EUR and JP. Some codes are unstable, these mostly mirror codes that were also unstable in version 1.0

### CODE REVIEW

**Comment by JourneyOver** [comment]
Okay so let's start this off. There are several changes that you are going to need to make before this is allowed to be merged in, as several things are not supported in luma's cheat engine.

1. Remove any japanese naming. Example:
```
カジュアルモードに変更
[Change casual mode v1.1]
```
should just be
```
[Change casual mode v1.1]
```

2. Remove all notes below the codes (both english and japanese) and if they are needed try to fit them into the name of the cheat without making the name of the cheat super long.

3. Things like this need to be removed (any cheats that require a person to need to go and edit the code to make it work):
```
[Difficulty change v1.1]
B05C6CF8 00000000
2000003D 0000000X <- 0;Normal, 1;Hard
D2000000 00000000
```

You can instead make multiple different codes if you would like for those types. Example:
```
[Difficulty change Normal v1.1]
B05C6CF8 00000000
2000003D 00000000
D2000000 00000000

[Difficulty change Hard v1.1]
B05C6CF8 00000000
2000003D 00000001
D2000000 00000000
```

4. Remove all:
```[++(Random name)++]```, ```[--]```

5. Preferably try to have the version of the game the code corresponds to in the name of the cheat.

**Comment by Anaklumos12** [comment]
Hey thank you for the guidelines. I didn't know about some of these limitations and plan on fixing it.

Quick question about removing comments:

```
[Change Starting Positions of Anyone in Preparations Menu (including enemy)]
002F960C E1500000
002F961C EA000007
002F9650 E3A00001
00307674 E3100B02
003076DC E3100B02
D2000000 00000000
{Enemy's danger area view button is change from A to Y}
````

If the comment `Enemy's danger area view button is change from A to Y` is built into the name, the resulting cheat name will be too long.  The cheat name also cannot be shortened without losing important information. Is it reasonable to leave the comment there, or will it crash Luma?

 The cheat can be used without knowledge of the comment, but I don't want to delete it if it is not necessary.

**Comment by JourneyOver** [comment]
I haven't messed with luma in ages but it's just not supported with luma cheat menu and we have required notes to be removed (and added to the cheat name if possible) since the beginning of this database and I don't see that changing anytime soon.

> There are cases in the old files where a cheat does not have a comment, making it practically unusable. For example, the cheat [Can Get both Dean and Sonya v1.0] requires a button prompt in a specific area of the game, but because there were no comments it was really difficult to use.

Yes I know, this is due to 99% of the database coming from fort42 back when it was at its end, we pulled the database and a lot of codes didn't come with their notes that was on the page, and then ones that did we incorporated into the cheat names where we could otherwise we deleted the notes.

**Comment by Anaklumos12** [comment]
Got it, I'll delete the notes and do what I can.

**Comment by JourneyOver** [comment]
To add to this as I do need to ask, since it was brought up in flagbrew discord, did you remove all `v1.0` codes? if you did please re-add them back, unless you updated all the `v1.0` to work on `v1.1` and they also still work on `v1.0`

Due to the way things are with checkpoint we don't really remove older versions of codes unless the updated code works for both whatever version it was updated for plus the older version as well, or if the code just straight up doesn't work ofc.

**Comment by Anaklumos12** [comment]
I was about to ask you a question about this actually. I have working codes for all regions and both version `1.0` and `1.1`. I was planning on adding them back, should I merge the codes for both versions into the same file, or make a different file for each version?

**Comment by JourneyOver** [comment]
They have to be in the same file because otherwise there would be a conflict since checkpoint requires the `Title ID` to be exact.

**Comment by Anaklumos12** [comment]
Should be fine now unless I've missed something

**Comment by JourneyOver** [comment]
From what I can tell it all looks good now, so thanks a bunch!

**Pull request merged**
