### PR TITLE
Update 000400000011C400.txt

### PR DESCRIPTION
**Pull request by Mattlau04**
video proof of the cheats working: https://youtu.be/v7K2q-w-31M

### CODE REVIEW

**Comment by JourneyOver** [comment]
That proof you posted, is CTRPF/Action replay, what sharkive is used for is Rosalina's cheat menu, not CTRPF menu, so unless you get proof of codes working with rosalina's cheat menu instead this will stay unmerged.

**Comment by hexthat** [comment]
Nanquitas Luma plugin and CTRPF should standard mod... idk why it isnt Rosalina's cheat stuff isnt very good

**Comment by JourneyOver** [comment]
1. Because last I checked Nanquitas's luma plugin menu isn't even officially in luma at all, while Rosalina's cheat menu is well officially in luma

2. Also last I checked Nanquitas doesn't even support his luma plugin menu anymore either, as it was kind of a one and done thing.

3. CTRPF requires NTR, either being from Nanquitas's luma plugin menu, or BootNTR, which the latter does not work for some games on the O3DS.

4. Rosalina's cheat menu, doesn't need any extra downloads really to get working, you only need luma (which if your running CFW then you 100% of the time already have luma) tbh as people can manually download codes if they really wanted to. sharkive is just a convenience tool.

5. Rosalina's cheat menu while it has some bugs, works on both N3DS/O3DS and every game without any issues what's so ever, the only thing that may not work is the actual cheat codes that you are trying to use and that could be for various reasons.

**Comment by hexthat** [comment]
I got 11.10-43U with it and on N3DSXL

out of your 6 reasons only 1 seems relevant #6, Nanquitas doesn't work on O3DS? ... seems like a good reason why it is not standard. I don't mean to argue but...

#1 Nobody cares if something is official or not, if they did they probably wouldn't have a modded 3ds.

#2 is his work copyrighted? why can't someone else use it

#3 I'm not sure what your trying to say here, so Nanquitas's luma plugin menu works but not BootNTR?

#4 are you trying to prove my point or yours?

#5 ? people are too dump to follow a few more steps

**Comment by SpiredMoth** [comment]
Clarifying Journey's points:

1. NTR was never added to the guide, so many people don't know about it. Far fewer know that Nanquitas's new 3gx version exists.
2. So far Nanquitas has released only 1 build (many months ago) of his Luma fork with the 3gx loader, and there has been no move, by Nanquitas or anyone else, to get it integrated into official Luma.
3. CTRPF is too large to be run through NTR for extended memory games played on O3DS. Some examples of extended memory games: Pokémon Sun/Moon/Ultra Sun/Ultra Moon, Super Smash Bros., Monster Hunter
4. Unless your cheats use custom ASM routines, they should be fully compatible with the latest Luma nightlies, and the eventual next release.
5. If you'd spent any time in troubleshooting channels (like the ones on the Nintendo Homebrew or FlagBrew Discord servers), you'd be aware (sometimes painfully) that many people have trouble with incredibly simple tasks like the current CFW installation process (arguably the easiest it has *ever* been). You really expect them to be able to successfully follow instructions that aren't nearly as user-friendly or well-maintained?

**Comment by Mattlau04** [comment]
the thing i use to record (kit kat slim) crash on the nightly release so i'm gonna try on latest stable

**Comment by Mattlau04** [comment]
well i can't tell if it's because i use an old version or it's just not compatible but Generate (Shiny) Pokémon (DexNav) for V1.4 crash when encontering the pokemon

**Comment by Mattlau04** [comment]
also some cheats aren't showing in the menu, is there a limit on many you can have?

**Comment by Mattlau04** [comment]
the only one that showed in the list apart from Generate (Shiny) Pokémon (DexNav) for V1.4 was 100% catch rate v1.4 and i can confirm it work

**Comment by JourneyOver** [comment]
Gah I'll just deal with testing myself sometime after I get off work today..

**Comment by Mattlau04** [comment]
ok thanks!

**Comment by hexthat** [comment]
@SpiredMoth thank you, for clarifying some of that up for me. I understand why it isn't standard, or integrated into official Luma is because it doesn't work on old systems.

Literally the only reason I found it is because I was having issues making codes with just Luma Memory Viewer... so i did google and found Nanquitas amazing work. Now I can Dev gatecodes 100% from my N3DSXL with ease.

**Comment by JourneyOver** [comment]
@Mattlau04 	you obviously didn't test your codes very well or something, as every code you have added I have yet to get working a single time, and half the time they end up leading to a crash after a little bit, even the supposed one that you said "the 100% catch rate 1.4" was working, doesn't work.. All this testing on the latest release of OR and the latest nightly of luma.

so again like I told you in your last PR will have to pass on this PR as the codes you have tried to provide do not work.

**Comment by iSharingan** [comment]
I have reason to suspect 3DS type (n2DS, o3DS, etc.) and/or certain Luma/NTR settings may have something to do with whether these codes work or not. Triforce Heroes is a prime example of this theory, as certain pieces of data are stored differently in RAM on o3DS versus n3DS.

**Comment by CoderTonyChan** [comment]
I will test [(START+L)Wild Pokemon Shiny, (START+R)Disable v1.4] tonight on citra

**Comment by GriffinG1** [comment]
Please do not post on closed pull requests. The codes won't miraculously start working now, and Citra isn't a good stand in for native hardware in this case.

**Pull request closed without merging**
