### PR TITLE
begin restoring "broken" pointer codes

### PR DESCRIPTION
**Pull request by SpiredMoth**
Start of a fix to #73

- a3c4852
    - [x] `db/0004000000137E00.txt` New Super Mario Bros. 2: Gold Edition (USA)
- d5d185c
    - [x] `db/00040000000AE400.txt` Monster Hunter 3 Ultimate (USA)
- 65a5b46
    - [x] `db/0004000000197100.txt` Monster Hunter XX Double Cross (JPN)
- f5ab051
    - [x] `db/0004000000132700.txt` Mario & Luigi: Paper Jam (USA)
- dfb03cb
    - [x] `db/00040000001D3A00.txt` Bloodstained: Curse of the Moon (JPN)
    - [x] `db/00040000001D4000.txt` Bloodstained: Curse of the Moon (USA)
- fed8c5c
    - [x] `db/00040000001A0400.txt` Super Mario Maker for Nintendo 3DS (USA)
- b261f55
    - [ ] `db/0004000000030800.txt` Mario Kart 7 (USA)
- 9097f43
    - [ ] `db/0004000000030800.txt` Mario Kart 7 (USA)
    - [x] `db/0004000000187000.txt` Monster Hunter Generations (USA)
- e122f23
    - [x] `db/0004000000049000.txt` Star Fox 64 3D (USA)
- ea79892
    - [x] `db/0004000000054000.txt` Super Mario 3D Land (USA)
- beea6aa
    - [x] `db/000400000007AE00.txt` New Super Mario Bros. 2 (USA)
- 3e44df6
    - [ ] `db/0004000000030800.txt` Mario Kart 7 (USA)
    - [x] `db/00040000000D5A00.txt` Mario & Luigi: Dream Team (USA)

Can be merged if you want or you can wait for somebody (me or someone else) to finish what I started first. Reasons for not being complete (aside from me being too lazy to write a script to do it for me):

- ~~Monster Hunter XX Double Cross (JPN): massive diff~~ done
- Mario Kart 7 (USA): multiple removals

### CODE REVIEW

**Comment by bugjp2** [comment]
ok so idk where i can make this code request but could puzzle dragons and mario puzzle dragon get codes if possible didnt see it listen on my cheats after running sharkive i know the physical cart has codes on it for the action replay i have used it before jus wanted to get codes for the game again

**Comment by GriffinG1** [comment]
@bugjp2 nowhere on this repo, and certainly not on any random issue. Nobody in Flagbrew knows how to make codes. Look into them yourself.

**Comment by BernardoGiordano** [comment]
What's the status of this PR?

**Comment by JourneyOver** [comment]
Think it's still WIP, I'd ask spired though. Last time he said it could be merged whenever though.

**Comment by SpiredMoth** [comment]
MHXX turned out to be easier than I thought once I came at it from a different direction: reset the file to the commit before everything was removed then re-add any new codes from later commits

MK7 isn't as easy. I listed 3 commits above that each removed cheats, plus there have been a few valid cheat removals since I first made the issue, meaning that a merge conflict is likely.

You're welcome to merge this whenever. If you do, a post should be made in issue #73 noting that MK7 still needs to be done.

**Comment by SpiredMoth** [comment]
Not as many removed cheats as I thought for MK7 so it wasn't hard to do it by hand.

Ready to be merged, unless you think some things should be reorganized.

**Comment by BernardoGiordano** [comment]
thank you

**Pull request merged**
