### PR TITLE
Sorted and added new codes

### PR DESCRIPTION
**Pull request by yor-so**
Added code for always on bike, rebattle Ho-Oh and Lugia.
Credits to Sc0tline user in gbatemp https://gbatemp.net/threads/gateway-cheats.402900/page-168

### CODE REVIEW

**Comment by JourneyOver** [comment]
Please remove any `{NOTES}` as they are not supported by lumas cheat engine.

**Comment by yor-so** [comment]
> Please remove any `{NOTES}` as they are not supported by lumas cheat engine.

Done! Thanks.

**Comment by yor-so** [comment]
I sorted all pokemon crystal codes, making them easier to navigate.

**Comment by JourneyOver** [comment]
LGTM - Thanks

**Pull request merged**
