### PR TITLE
Update 00040000000EDF00.txt

### PR DESCRIPTION
**Pull request by DeltaTheWolf**
Some EU codes work for the US version.

### CODE REVIEW

**Comment by JourneyOver** [comment]
Lgtm, thanks!

**Comment by adueppen** [comment]
Out of curiosity, what do codes like "power hits" and "power health" do?

**Comment by DeltaTheWolf** [comment]
Power hits makes it so every hit you do does 999%.
Power health makes you take no damage.

**Comment by adueppen** [comment]
OK thanks! Do they work on the latest update of SSB?

**Comment by adueppen** [comment]
I tried them (I'm on 1.1.7 downloadable, with the DLC) and neither of those 2 codes worked.

**Comment by JourneyOver** [comment]
If a code or something is not working please make an issue instead of reporting it in a closed PR

**Pull request merged**
