### PR TITLE
Create LoZ:OoT Codes

### PR DESCRIPTION
**Pull request by Th4nat0s1s**
GateShark Codes for LoZ:OoT 3DS

### CODE REVIEW

**Comment by JourneyOver** [comment]
So a couple things and the reason I am closing this and not merging it in.

1.  You named the file incorrectly, it is supposed to be `TitleID.txt` ie for LoZ:OoT it would be `0004000000033500.txt`

2. You kept in the info about fort42 when that should of been removed.

3. (Main reason on why I'm closing this) The codes that you are trying to add are complete duplicates of the codes that are already in the DB for the game/region/version that you are trying to add.

**Comment by Th4nat0s1s** [comment]
Well the only reason I suggested it was due to the fact that Sharkive
scanned but never showed those games so I assumed they weren't in the
archive

Secondly, I was fairly new to how all that worked but I do know now that I
miss named the file.

Lastly... Ok, you do you.

**Comment by Th4nat0s1s** [comment]
And what is fort42?

**Comment by JourneyOver** [comment]
You need to have opened and saved the game at least once before it shows up in sharkive, also there is a bug in sharkive currently that may require you to go onto your SD card and delete the titles.sha file from 3ds/sharkive directory (bug will be fixed eventually but sharkive is on the lower end of the spectrum of things atm)

But trust me when I say that the game is in the DB for multiple regions, and the codes you had provided for the game was already there from the start.

As for fort42, it used to be the main site that you'd go to for various gateshark/actionreplay codes, but for some reason or another the owner of the site decided to shut the site down, luckily some people was able to grab a recent dump of all the codes from the site and well let's just say the DB would be very empty if it wasn't for that dump as literally everything from the dump ended up here albiet we have slowly been removing/fixing broken codes over time.

**Pull request closed without merging**
