### PR TITLE
Update 00040000000F7B00.txt

### PR DESCRIPTION
**Pull request by Iounpero**
Is it okay to add these cheats to inazuma eleven 3 bomber?(they should work for spark too)
experience multiplier
99-0
no encounter end instant encounter

### CODE REVIEW

**Comment by JourneyOver** [comment]
Have you confirmed that these cheats work on original Hardware using the Rosalina menu (Luma3DS) cheat engine

**Comment by Iounpero** [comment]
Can luma's cheat engine run any action replay code?Or just a limited amount?

**Comment by JourneyOver** [comment]
Last I checked it can load both Gateshark codes and CTRPF-AR codes, but I would suggest you just try the codes on original 3ds hardware to see if they work or not.

**Comment by JourneyOver** [comment]
Never got a response back on if these cheats worked on original hardware using the rosalina menu (Luma3DS) cheat engine, so closing for now.. if I get a response back then I may re-open/merge..

**Pull request closed without merging**
